
pipelines:
  - name: tap
    dnstap:
      listen-ip: 0.0.0.0
      listen-port: 6000
    routing-policy:
      forward: [mqtt-logger]

  - name: mqtt-logger
    mqtt:
      remote-address: "127.0.0.1"
      remote-port: 1883
      topic: "dns/logs"
      qos: 1
      protocol-version: "auto"
      mode: "flat-json"
